// Package magicmarketsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package magicmarketsapi

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BalanceEnvelopeStatus.
const (
	BalanceEnvelopeStatusOk BalanceEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the BalanceEnvelopeStatus enum.
func (e BalanceEnvelopeStatus) Valid() bool {
	switch e {
	case BalanceEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for BetResponseExchangeRole.
const (
	BetResponseExchangeRoleLessThanNil BetResponseExchangeRole = "<nil>"
	BetResponseExchangeRoleMaker       BetResponseExchangeRole = "maker"
	BetResponseExchangeRoleTaker       BetResponseExchangeRole = "taker"
)

// Valid indicates whether the value is a known member of the BetResponseExchangeRole enum.
func (e BetResponseExchangeRole) Valid() bool {
	switch e {
	case BetResponseExchangeRoleLessThanNil:
		return true
	case BetResponseExchangeRoleMaker:
		return true
	case BetResponseExchangeRoleTaker:
		return true
	default:
		return false
	}
}

// Defines values for BetTypeInfoEnvelopeStatus.
const (
	BetTypeInfoEnvelopeStatusOk BetTypeInfoEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the BetTypeInfoEnvelopeStatus enum.
func (e BetTypeInfoEnvelopeStatus) Valid() bool {
	switch e {
	case BetTypeInfoEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for BetslipCreateEnvelopeStatus.
const (
	BetslipCreateEnvelopeStatusOk BetslipCreateEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the BetslipCreateEnvelopeStatus enum.
func (e BetslipCreateEnvelopeStatus) Valid() bool {
	switch e {
	case BetslipCreateEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for BetslipCreateRequestBetslipType.
const (
	BetslipCreateRequestBetslipTypeLay    BetslipCreateRequestBetslipType = "lay"
	BetslipCreateRequestBetslipTypeNormal BetslipCreateRequestBetslipType = "normal"
	BetslipCreateRequestBetslipTypeParlay BetslipCreateRequestBetslipType = "parlay"
)

// Valid indicates whether the value is a known member of the BetslipCreateRequestBetslipType enum.
func (e BetslipCreateRequestBetslipType) Valid() bool {
	switch e {
	case BetslipCreateRequestBetslipTypeLay:
		return true
	case BetslipCreateRequestBetslipTypeNormal:
		return true
	case BetslipCreateRequestBetslipTypeParlay:
		return true
	default:
		return false
	}
}

// Defines values for BetslipCreateResponseBetslipType.
const (
	BetslipCreateResponseBetslipTypeLay    BetslipCreateResponseBetslipType = "lay"
	BetslipCreateResponseBetslipTypeNormal BetslipCreateResponseBetslipType = "normal"
	BetslipCreateResponseBetslipTypeParlay BetslipCreateResponseBetslipType = "parlay"
)

// Valid indicates whether the value is a known member of the BetslipCreateResponseBetslipType enum.
func (e BetslipCreateResponseBetslipType) Valid() bool {
	switch e {
	case BetslipCreateResponseBetslipTypeLay:
		return true
	case BetslipCreateResponseBetslipTypeNormal:
		return true
	case BetslipCreateResponseBetslipTypeParlay:
		return true
	default:
		return false
	}
}

// Defines values for BetslipEnvelopeStatus.
const (
	BetslipEnvelopeStatusOk BetslipEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the BetslipEnvelopeStatus enum.
func (e BetslipEnvelopeStatus) Valid() bool {
	switch e {
	case BetslipEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for BetslipListEnvelopeStatus.
const (
	BetslipListEnvelopeStatusOk BetslipListEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the BetslipListEnvelopeStatus enum.
func (e BetslipListEnvelopeStatus) Valid() bool {
	switch e {
	case BetslipListEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for BetslipResponseBetslipType.
const (
	BetslipResponseBetslipTypeLay    BetslipResponseBetslipType = "lay"
	BetslipResponseBetslipTypeNormal BetslipResponseBetslipType = "normal"
	BetslipResponseBetslipTypeParlay BetslipResponseBetslipType = "parlay"
)

// Valid indicates whether the value is a known member of the BetslipResponseBetslipType enum.
func (e BetslipResponseBetslipType) Valid() bool {
	switch e {
	case BetslipResponseBetslipTypeLay:
		return true
	case BetslipResponseBetslipTypeNormal:
		return true
	case BetslipResponseBetslipTypeParlay:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeStatus.
const (
	Error ErrorEnvelopeStatus = "error"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeStatus enum.
func (e ErrorEnvelopeStatus) Valid() bool {
	switch e {
	case Error:
		return true
	default:
		return false
	}
}

// Defines values for EventInfoEventType.
const (
	EventInfoEventTypeMultirunner EventInfoEventType = "multirunner"
	EventInfoEventTypeNormal      EventInfoEventType = "normal"
	EventInfoEventTypeParlay      EventInfoEventType = "parlay"
)

// Valid indicates whether the value is a known member of the EventInfoEventType enum.
func (e EventInfoEventType) Valid() bool {
	switch e {
	case EventInfoEventTypeMultirunner:
		return true
	case EventInfoEventTypeNormal:
		return true
	case EventInfoEventTypeParlay:
		return true
	default:
		return false
	}
}

// Defines values for HeartbeatCancelEnvelopeStatus.
const (
	HeartbeatCancelEnvelopeStatusOk HeartbeatCancelEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the HeartbeatCancelEnvelopeStatus enum.
func (e HeartbeatCancelEnvelopeStatus) Valid() bool {
	switch e {
	case HeartbeatCancelEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for HeartbeatEnvelopeStatus.
const (
	HeartbeatEnvelopeStatusOk HeartbeatEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the HeartbeatEnvelopeStatus enum.
func (e HeartbeatEnvelopeStatus) Valid() bool {
	switch e {
	case HeartbeatEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for HeartbeatListEnvelopeStatus.
const (
	HeartbeatListEnvelopeStatusOk HeartbeatListEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the HeartbeatListEnvelopeStatus enum.
func (e HeartbeatListEnvelopeStatus) Valid() bool {
	switch e {
	case HeartbeatListEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for OrderCreateRequestExchangeMode.
const (
	OrderCreateRequestExchangeModeDark        OrderCreateRequestExchangeMode = "dark"
	OrderCreateRequestExchangeModeMakeAndTake OrderCreateRequestExchangeMode = "make_and_take"
	OrderCreateRequestExchangeModeTakeOnly    OrderCreateRequestExchangeMode = "take_only"
)

// Valid indicates whether the value is a known member of the OrderCreateRequestExchangeMode enum.
func (e OrderCreateRequestExchangeMode) Valid() bool {
	switch e {
	case OrderCreateRequestExchangeModeDark:
		return true
	case OrderCreateRequestExchangeModeMakeAndTake:
		return true
	case OrderCreateRequestExchangeModeTakeOnly:
		return true
	default:
		return false
	}
}

// Defines values for OrderEnvelopeStatus.
const (
	OrderEnvelopeStatusOk OrderEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the OrderEnvelopeStatus enum.
func (e OrderEnvelopeStatus) Valid() bool {
	switch e {
	case OrderEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for OrderListEnvelopeStatus.
const (
	OrderListEnvelopeStatusOk OrderListEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the OrderListEnvelopeStatus enum.
func (e OrderListEnvelopeStatus) Valid() bool {
	switch e {
	case OrderListEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for OrderResponseExchangeMode.
const (
	OrderResponseExchangeModeDark        OrderResponseExchangeMode = "dark"
	OrderResponseExchangeModeLessThanNil OrderResponseExchangeMode = "<nil>"
	OrderResponseExchangeModeMakeAndTake OrderResponseExchangeMode = "make_and_take"
	OrderResponseExchangeModeTakeOnly    OrderResponseExchangeMode = "take_only"
)

// Valid indicates whether the value is a known member of the OrderResponseExchangeMode enum.
func (e OrderResponseExchangeMode) Valid() bool {
	switch e {
	case OrderResponseExchangeModeDark:
		return true
	case OrderResponseExchangeModeLessThanNil:
		return true
	case OrderResponseExchangeModeMakeAndTake:
		return true
	case OrderResponseExchangeModeTakeOnly:
		return true
	default:
		return false
	}
}

// Defines values for OrderResponseOrderType.
const (
	OrderResponseOrderTypeBrokerage OrderResponseOrderType = "brokerage"
	OrderResponseOrderTypeCashout   OrderResponseOrderType = "cashout"
	OrderResponseOrderTypeCustom    OrderResponseOrderType = "custom"
	OrderResponseOrderTypeLay       OrderResponseOrderType = "lay"
	OrderResponseOrderTypeNormal    OrderResponseOrderType = "normal"
	OrderResponseOrderTypeParlay    OrderResponseOrderType = "parlay"
)

// Valid indicates whether the value is a known member of the OrderResponseOrderType enum.
func (e OrderResponseOrderType) Valid() bool {
	switch e {
	case OrderResponseOrderTypeBrokerage:
		return true
	case OrderResponseOrderTypeCashout:
		return true
	case OrderResponseOrderTypeCustom:
		return true
	case OrderResponseOrderTypeLay:
		return true
	case OrderResponseOrderTypeNormal:
		return true
	case OrderResponseOrderTypeParlay:
		return true
	default:
		return false
	}
}

// Defines values for ParlayLegOutcome.
const (
	ParlayLegOutcomeL           ParlayLegOutcome = "l"
	ParlayLegOutcomeLV          ParlayLegOutcome = "l/v"
	ParlayLegOutcomeLW          ParlayLegOutcome = "l/w"
	ParlayLegOutcomeLessThanNil ParlayLegOutcome = "<nil>"
	ParlayLegOutcomeUnknown     ParlayLegOutcome = "unknown"
	ParlayLegOutcomeV           ParlayLegOutcome = "v"
	ParlayLegOutcomeVW          ParlayLegOutcome = "v/w"
	ParlayLegOutcomeW           ParlayLegOutcome = "w"
)

// Valid indicates whether the value is a known member of the ParlayLegOutcome enum.
func (e ParlayLegOutcome) Valid() bool {
	switch e {
	case ParlayLegOutcomeL:
		return true
	case ParlayLegOutcomeLV:
		return true
	case ParlayLegOutcomeLW:
		return true
	case ParlayLegOutcomeLessThanNil:
		return true
	case ParlayLegOutcomeUnknown:
		return true
	case ParlayLegOutcomeV:
		return true
	case ParlayLegOutcomeVW:
		return true
	case ParlayLegOutcomeW:
		return true
	default:
		return false
	}
}

// Defines values for PositionEnvelopeStatus.
const (
	PositionEnvelopeStatusOk PositionEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the PositionEnvelopeStatus enum.
func (e PositionEnvelopeStatus) Valid() bool {
	switch e {
	case PositionEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for XRatesEnvelopeStatus.
const (
	XRatesEnvelopeStatusOk XRatesEnvelopeStatus = "ok"
)

// Valid indicates whether the value is a known member of the XRatesEnvelopeStatus enum.
func (e XRatesEnvelopeStatus) Valid() bool {
	switch e {
	case XRatesEnvelopeStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PostV2OrdersCloseMany200JSONResponseBodyStatus.
const (
	PostV2OrdersCloseMany200JSONResponseBodyStatusOk PostV2OrdersCloseMany200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the PostV2OrdersCloseMany200JSONResponseBodyStatus enum.
func (e PostV2OrdersCloseMany200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case PostV2OrdersCloseMany200JSONResponseBodyStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for GetV2StreamParamsLang.
const (
	En     GetV2StreamParamsLang = "en"
	Ko     GetV2StreamParamsLang = "ko"
	ZhHans GetV2StreamParamsLang = "zh-hans"
)

// Valid indicates whether the value is a known member of the GetV2StreamParamsLang enum.
func (e GetV2StreamParamsLang) Valid() bool {
	switch e {
	case En:
		return true
	case Ko:
		return true
	case ZhHans:
		return true
	default:
		return false
	}
}

// BalanceEnvelope defines model for BalanceEnvelope.
type BalanceEnvelope struct {
	Data   *BalanceResponse       `json:"data,omitempty"`
	Status *BalanceEnvelopeStatus `json:"status,omitempty"`
}

// BalanceEnvelopeStatus defines model for BalanceEnvelope.Status.
type BalanceEnvelopeStatus string

// BalanceResponse defines model for BalanceResponse.
type BalanceResponse struct {
	// Balance Current account balance
	Balance StakeTuple `json:"balance"`

	// OpenStake Total stake on open bets, positive
	OpenStake StakeTuple `json:"open_stake"`

	// SmartCredit Smart credit, or null when the account has none
	SmartCredit *StakeTuple `json:"smart_credit"`
}

// BetResponse Individual bet within an order
type BetResponse struct {
	BetID *int `json:"bet_id,omitempty"`

	// BetType Bet type string — see "Sports & bet types" in the introduction.
	BetType      *string                  `json:"bet_type,omitempty"`
	CcyRate      *float64                 `json:"ccy_rate,omitempty"`
	EventID      *string                  `json:"event_id,omitempty"`
	ExchangeRole *BetResponseExchangeRole `json:"exchange_role,omitempty"`
	GotPrice     *float64                 `json:"got_price,omitempty"`

	// GotStake [currency, amount] tuple, e.g. ["USDT", 115.38]. Generated as an untyped array because oapi-codegen cannot express an OpenAPI 3.1 tuple; magicmarkets.Stake is the typed equivalent.
	GotStake     *StakeTuple `json:"got_stake,omitempty"`
	OrderCcyRate *float64    `json:"order_ccy_rate,omitempty"`
	OrderID      *int        `json:"order_id,omitempty"`
	ProfitLoss   *StakeTuple `json:"profit_loss,omitempty"`
	Reconciled   *bool       `json:"reconciled,omitempty"`

	// Sport Sport code — see "Sports & bet types" in the introduction.
	Sport *string `json:"sport,omitempty"`

	// Status Bet status
	Status *struct {
		// Code e.g. matched, failed, settled
		Code *string `json:"code,omitempty"`

		// Reason Human-readable failure reason; present only when `code` is `failed`
		Reason      *string     `json:"reason,omitempty"`
		ResponsePmm *PriceLevel `json:"response_pmm,omitempty"`
	} `json:"status,omitempty"`
	WantPrice *float64 `json:"want_price,omitempty"`

	// WantStake [currency, amount] tuple, e.g. ["USDT", 115.38]. Generated as an untyped array because oapi-codegen cannot express an OpenAPI 3.1 tuple; magicmarkets.Stake is the typed equivalent.
	WantStake *StakeTuple `json:"want_stake,omitempty"`
}

// BetResponseExchangeRole defines model for BetResponse.ExchangeRole.
type BetResponseExchangeRole string

// BetTypeInfoEnvelope defines model for BetTypeInfoEnvelope.
type BetTypeInfoEnvelope struct {
	Data   *BetTypeInfoResponse       `json:"data,omitempty"`
	Status *BetTypeInfoEnvelopeStatus `json:"status,omitempty"`
}

// BetTypeInfoEnvelopeStatus defines model for BetTypeInfoEnvelope.Status.
type BetTypeInfoEnvelopeStatus string

// BetTypeInfoResponse defines model for BetTypeInfoResponse.
type BetTypeInfoResponse struct {
	// BetTypeDescription Human-readable bet type label
	BetTypeDescription *string `json:"bet_type_description,omitempty"`

	// Sport Display name for the sport (e.g. "Football")
	Sport *string `json:"sport,omitempty"`

	// WinlossGrid 20x20 grid of `w`/`l`/`p` (push)/`v` (void) outcomes
	WinlossGrid *[][]string `json:"winloss_grid,omitempty"`
}

// BetslipCreateEnvelope defines model for BetslipCreateEnvelope.
type BetslipCreateEnvelope struct {
	// Data Create (POST) response; carries no prices. Poll GET or watch the stream for the quote.
	Data   *BetslipCreateResponse       `json:"data,omitempty"`
	Status *BetslipCreateEnvelopeStatus `json:"status,omitempty"`
}

// BetslipCreateEnvelopeStatus defines model for BetslipCreateEnvelope.Status.
type BetslipCreateEnvelopeStatus string

// BetslipCreateRequest defines model for BetslipCreateRequest.
type BetslipCreateRequest struct {
	// BetType Bet type string (required for normal/lay) — see "Sports & bet types" in the introduction.
	BetType        *string                          `json:"bet_type,omitempty"`
	BetslipType    *BetslipCreateRequestBetslipType `json:"betslip_type,omitempty"`
	EquivalentBets *bool                            `json:"equivalent_bets,omitempty"`

	// EventID Event ID (required for normal/lay)
	EventID *string `json:"event_id,omitempty"`

	// ExcludeDanger When true, only liquidity sources that do not hold bets in danger status are used. When false or omitted, all available liquidity sources are used.
	ExcludeDanger *bool `json:"exclude_danger,omitempty"`

	// Legs Parlay legs (required for parlay, 2–10 legs)
	Legs *[]struct {
		BetType string `json:"bet_type"`
		EventID string `json:"event_id"`
		Sport   string `json:"sport"`
	} `json:"legs,omitempty"`

	// Sport Sport code (required for normal/lay) — see "Sports & bet types" in the introduction.
	Sport    *string `json:"sport,omitempty"`
	UserData *string `json:"user_data,omitempty"`
}

// BetslipCreateRequestBetslipType defines model for BetslipCreateRequest.BetslipType.
type BetslipCreateRequestBetslipType string

// BetslipCreateResponse Create (POST) response; carries no prices. Poll GET or watch the stream for the quote.
type BetslipCreateResponse struct {
	// BetType Bet type string — see "Sports & bet types" in the introduction.
	BetType *string `json:"bet_type,omitempty"`

	// BetTypeDescription Human-readable label, e.g. Home, Over 1.5 (Asian)
	BetTypeDescription *string                           `json:"bet_type_description,omitempty"`
	BetslipID          *string                           `json:"betslip_id,omitempty"`
	BetslipType        *BetslipCreateResponseBetslipType `json:"betslip_type,omitempty"`
	CloseReason        *string                           `json:"close_reason,omitempty"`

	// CustomerCcy Customer's base currency code
	CustomerCcy      *string `json:"customer_ccy,omitempty"`
	CustomerUsername *string `json:"customer_username,omitempty"`

	// EquivalentBets Whether equivalent bets are included
	EquivalentBets *bool `json:"equivalent_bets,omitempty"`

	// EventID Event identifier, e.g. 2026-06-15,1001,2002
	EventID *string `json:"event_id,omitempty"`

	// ExpiryTS Unix timestamp when the betslip expires
	ExpiryTS *float64 `json:"expiry_ts,omitempty"`
	IsOpen   *bool    `json:"is_open,omitempty"`

	// Legs Parlay legs (only present for parlay betslips)
	Legs *ParlayLegList `json:"legs,omitempty"`

	// Sport Sport code — see "Sports & bet types" in the introduction.
	Sport    *string `json:"sport,omitempty"`
	UserData *string `json:"user_data,omitempty"`
}

// BetslipCreateResponseBetslipType defines model for BetslipCreateResponse.BetslipType.
type BetslipCreateResponseBetslipType string

// BetslipEnvelope defines model for BetslipEnvelope.
type BetslipEnvelope struct {
	Data   *BetslipResponse       `json:"data,omitempty"`
	Status *BetslipEnvelopeStatus `json:"status,omitempty"`
}

// BetslipEnvelopeStatus defines model for BetslipEnvelope.Status.
type BetslipEnvelopeStatus string

// BetslipListEnvelope defines model for BetslipListEnvelope.
type BetslipListEnvelope struct {
	// Data Array of betslip IDs
	Data   *[]string                  `json:"data,omitempty"`
	Status *BetslipListEnvelopeStatus `json:"status,omitempty"`
}

// BetslipListEnvelopeStatus defines model for BetslipListEnvelope.Status.
type BetslipListEnvelopeStatus string

// BetslipResponse defines model for BetslipResponse.
type BetslipResponse struct {
	// BetType Bet type string — see "Sports & bet types" in the introduction.
	BetType *string `json:"bet_type,omitempty"`

	// BetTypeDescription Human-readable label, e.g. Home, Over 1.5 (Asian)
	BetTypeDescription *string                     `json:"bet_type_description,omitempty"`
	BetslipID          *string                     `json:"betslip_id,omitempty"`
	BetslipType        *BetslipResponseBetslipType `json:"betslip_type,omitempty"`
	CloseReason        *string                     `json:"close_reason,omitempty"`

	// CustomerCcy Customer's base currency code
	CustomerCcy      *string `json:"customer_ccy,omitempty"`
	CustomerUsername *string `json:"customer_username,omitempty"`

	// EquivalentBets Whether equivalent bets are included
	EquivalentBets *bool `json:"equivalent_bets,omitempty"`

	// EventID Event identifier, e.g. 2026-06-15,1001,2002
	EventID *string `json:"event_id,omitempty"`

	// ExpiryTS Unix timestamp when the betslip expires
	ExpiryTS *float64 `json:"expiry_ts,omitempty"`
	IsOpen   *bool    `json:"is_open,omitempty"`

	// Legs Parlay legs (only present for parlay betslips)
	Legs *ParlayLegList `json:"legs,omitempty"`

	// PriceList Prices sorted descending (best price first). May be empty until quotes arrive, or when no source is currently quoting.
	PriceList *[]PriceLevel `json:"price_list,omitempty"`

	// Sport Sport code — see "Sports & bet types" in the introduction.
	Sport *string `json:"sport,omitempty"`

	// Total Sum of max stakes across all price levels, or null if no prices
	Total    *StakeTuple `json:"total,omitempty"`
	UserData *string     `json:"user_data,omitempty"`
}

// BetslipResponseBetslipType defines model for BetslipResponse.BetslipType.
type BetslipResponseBetslipType string

// ErrorEnvelope Standard error response. The shape of `data` varies by `code` — see the **Errors** section in the introduction and the named examples on each endpoint's error responses.
type ErrorEnvelope struct {
	// Code Stable machine-readable error code (e.g. `validation_error`, `not_found`, `forbidden`).
	Code string `json:"code"`

	// Data Variable. Null, string, or object — see examples.
	Data   interface{}         `json:"data,omitempty"`
	Status ErrorEnvelopeStatus `json:"status"`
}

// ErrorEnvelopeStatus defines model for ErrorEnvelope.Status.
type ErrorEnvelopeStatus string

// EventInfo defines model for EventInfo.
type EventInfo struct {
	// AwayID Normal events only
	AwayID   *int    `json:"away_id,omitempty"`
	AwayTeam *string `json:"away_team,omitempty"`

	// CompetitionCountry ISO country code (e.g. XE for England)
	CompetitionCountry *string             `json:"competition_country,omitempty"`
	CompetitionID      *int                `json:"competition_id,omitempty"`
	CompetitionName    *string             `json:"competition_name,omitempty"`
	Date               *openapi_types.Date `json:"date,omitempty"`

	// EndTime Race end time (multirunner events only)
	EndTime *time.Time `json:"end_time,omitempty"`

	// EventID null for parlay orders
	EventID   *string             `json:"event_id,omitempty"`
	EventName *string             `json:"event_name,omitempty"`
	EventType *EventInfoEventType `json:"event_type,omitempty"`

	// HomeID Normal events only
	HomeID   *int    `json:"home_id,omitempty"`
	HomeTeam *string `json:"home_team,omitempty"`

	// LegEventInfos Sub-event info for each leg (parlay orders only)
	LegEventInfos *[]EventInfo `json:"leg_event_infos,omitempty"`

	// Result Match or race result. The shape depends on the sport - see the `EventResult*` schemas. Null while the result is unknown.
	Result    *EventInfo_Result `json:"result,omitempty"`
	StartTime *time.Time        `json:"start_time,omitempty"`

	// Teams Runner list (multirunner events only)
	Teams *struct {
		Name   *string `json:"name,omitempty"`
		TeamID *int    `json:"team_id,omitempty"`
	} `json:"teams,omitempty"`
}

// EventInfoEventType defines model for EventInfo.EventType.
type EventInfoEventType string

// EventInfo_Result Match or race result. The shape depends on the sport - see the `EventResult*` schemas. Null while the result is unknown.
type EventInfo_Result struct {
	union json.RawMessage
}

// EventResultHockey Ice hockey. `tpN_*` are the three period scores; `tall_*` the regulation total; `pen_*` the penalty-shootout score.
type EventResultHockey struct {
	PenAway  *int `json:"pen_away,omitempty"`
	PenHome  *int `json:"pen_home,omitempty"`
	TallAway *int `json:"tall_away,omitempty"`
	TallHome *int `json:"tall_home,omitempty"`
	Tp1Away  *int `json:"tp1_away,omitempty"`
	Tp1Home  *int `json:"tp1_home,omitempty"`
	Tp2Away  *int `json:"tp2_away,omitempty"`
	Tp2Home  *int `json:"tp2_home,omitempty"`
	Tp3Away  *int `json:"tp3_away,omitempty"`
	Tp3Home  *int `json:"tp3_home,omitempty"`
}

// EventResultMatch Football and other two-half sports. `ht_*` are the half-time score and are omitted for single-period sports; `ft_*` are the full-time score.
type EventResultMatch struct {
	FtAway *int `json:"ft_away,omitempty"`
	FtHome *int `json:"ft_home,omitempty"`
	HtAway *int `json:"ht_away,omitempty"`
	HtHome *int `json:"ht_home,omitempty"`
}

// EventResultMultirunner Multirunner (outright) events.
type EventResultMultirunner struct {
	NonRunnerCount *int `json:"non_runner_count,omitempty"`

	// RunnerResults Finishing positions per runner
	RunnerResults *[]struct {
		// Position 1=first, 2=second, 0=unknown, -1=void, -2=non-runner, -3=eliminated
		Position *int `json:"position,omitempty"`
		TeamID   *int `json:"team_id,omitempty"`
	} `json:"runner_results,omitempty"`
}

// EventResultTableTennis Table tennis. `gameN_*` is the point score in game N (up to 7 games).
type EventResultTableTennis struct {
	Game1Away *int `json:"game1_away,omitempty"`
	Game1Home *int `json:"game1_home,omitempty"`
	Game2Away *int `json:"game2_away,omitempty"`
	Game2Home *int `json:"game2_home,omitempty"`
	Game3Away *int `json:"game3_away,omitempty"`
	Game3Home *int `json:"game3_home,omitempty"`
	Game4Away *int `json:"game4_away,omitempty"`
	Game4Home *int `json:"game4_home,omitempty"`
	Game5Away *int `json:"game5_away,omitempty"`
	Game5Home *int `json:"game5_home,omitempty"`
	Game6Away *int `json:"game6_away,omitempty"`
	Game6Home *int `json:"game6_home,omitempty"`
	Game7Away *int `json:"game7_away,omitempty"`
	Game7Home *int `json:"game7_home,omitempty"`
}

// EventResultTennis Tennis. `setN_pM` is player M's game count in set N.
type EventResultTennis struct {
	Set1P1 *int `json:"set1_p1,omitempty"`
	Set1P2 *int `json:"set1_p2,omitempty"`
	Set2P1 *int `json:"set2_p1,omitempty"`
	Set2P2 *int `json:"set2_p2,omitempty"`
	Set3P1 *int `json:"set3_p1,omitempty"`
	Set3P2 *int `json:"set3_p2,omitempty"`
	Set4P1 *int `json:"set4_p1,omitempty"`
	Set4P2 *int `json:"set4_p2,omitempty"`
	Set5P1 *int `json:"set5_p1,omitempty"`
	Set5P2 *int `json:"set5_p2,omitempty"`

	// WhoRetired 1 or 2 if a player retired, else 0 or null
	WhoRetired *int `json:"who_retired,omitempty"`
}

// HeartbeatCancelEnvelope Cancel response. `data` is always `null`.
type HeartbeatCancelEnvelope struct {
	Data   any                            `json:"data,omitempty"`
	Status *HeartbeatCancelEnvelopeStatus `json:"status,omitempty"`
}

// HeartbeatCancelEnvelopeStatus defines model for HeartbeatCancelEnvelope.Status.
type HeartbeatCancelEnvelopeStatus string

// HeartbeatEnvelope defines model for HeartbeatEnvelope.
type HeartbeatEnvelope struct {
	Data   *HeartbeatResponse       `json:"data,omitempty"`
	Status *HeartbeatEnvelopeStatus `json:"status,omitempty"`
}

// HeartbeatEnvelopeStatus defines model for HeartbeatEnvelope.Status.
type HeartbeatEnvelopeStatus string

// HeartbeatListEnvelope List response. Note the data is wrapped under a `heartbeats` key, unlike other list endpoints which return a flat array.
type HeartbeatListEnvelope struct {
	Data *struct {
		Heartbeats *[]HeartbeatResponse `json:"heartbeats,omitempty"`
	} `json:"data,omitempty"`
	Status *HeartbeatListEnvelopeStatus `json:"status,omitempty"`
}

// HeartbeatListEnvelopeStatus defines model for HeartbeatListEnvelope.Status.
type HeartbeatListEnvelopeStatus string

// HeartbeatResponse defines model for HeartbeatResponse.
type HeartbeatResponse struct {
	ExpiryTime  *time.Time `json:"expiry_time,omitempty"`
	HeartbeatID *string    `json:"heartbeat_id,omitempty"`
}

// OrderCreateRequest defines model for OrderCreateRequest.
type OrderCreateRequest struct {
	AcceptBetterPrice *bool  `json:"accept_better_price,omitempty"`
	AcceptPartialFill *bool  `json:"accept_partial_fill,omitempty"`
	BetslipID         string `json:"betslip_id"`

	// BookieMinStakes Optional per-source minimum stakes, keyed by source. A source is only used if it can take at least its minimum. Values are `[currency, amount]` tuples.
	BookieMinStakes *map[string]StakeTuple `json:"bookie_min_stakes,omitempty"`

	// CurrentScore Placement-time score assertion, `[home, away]`. When present, the order is rejected with `validation_error` / `non_field_errors: ["event_scores_dont_match"]` unless the value matches the live score the exchange holds for the event - use it to avoid placing on a price that has not reacted to a goal yet. Only meaningful for football: for sports without a goal-style running score, and while no score is known yet, the server assumes `[0, 0]` and rejects any other value. Omit the field to skip the check.
	CurrentScore *OrderCreateRequest_CurrentScore `json:"current_score,omitempty"`

	// Duration Order duration in seconds (default 15)
	Duration *float64 `json:"duration,omitempty"`

	// ExchangeMode How the order interacts with the exchange. `make_and_take`: fill against the best available liquidity first; any remaining stake is advertised on the exchange at your price, while the order keeps taking newly available liquidity. `take_only`: only consume available liquidity; remaining stake is never advertised and other orders cannot match against it. `dark`: like `make_and_take`, but the advertised remaining stake is hidden from other customers - they can still match it when their price crosses yours, but they cannot see your price until then. There is no post-only mode: no order type rests in the book without also taking crossing liquidity.
	ExchangeMode *OrderCreateRequestExchangeMode `json:"exchange_mode,omitempty"`

	// ExcludeDanger When true, only liquidity sources that do not hold bets in danger status are used. When false or omitted, all available liquidity sources are used.
	ExcludeDanger  *bool `json:"exclude_danger,omitempty"`
	ForceWantPrice *bool `json:"force_want_price,omitempty"`

	// KeepOpenIr Keep order open when event goes in-play
	KeepOpenIr *bool `json:"keep_open_ir,omitempty"`

	// MinTakerWantStake `dark` orders only (rejected on other modes): the minimum total stake another order must request to be allowed to match yours at your price point. Cannot exceed the order's own stake. Set it non-zero to stop small probe orders from discovering your price.
	MinTakerWantStake *StakeTuple `json:"min_taker_want_stake,omitempty"`

	// PlacerType Optional caller-supplied tag recorded against the order.
	PlacerType *string `json:"placer_type,omitempty"`

	// Price Desired decimal price. Off-tick prices are rounded down for back (`for`) orders and up for lay (`against`) orders; see "Price ticks".
	Price float64 `json:"price"`

	// RequestUUID Idempotency key
	RequestUUID *string `json:"request_uuid,omitempty"`

	// Stake [currency, amount] tuple, e.g. ["USDT", 115.38]. Generated as an untyped array because oapi-codegen cannot express an OpenAPI 3.1 tuple; magicmarkets.Stake is the typed equivalent.
	Stake    StakeTuple `json:"stake"`
	UserData *string    `json:"user_data,omitempty"`
}

// OrderCreateRequestCurrentScore0 defines model for OrderCreateRequest.CurrentScore.0.
type OrderCreateRequestCurrentScore0 = []int

// OrderCreateRequest_CurrentScore Placement-time score assertion, `[home, away]`. When present, the order is rejected with `validation_error` / `non_field_errors: ["event_scores_dont_match"]` unless the value matches the live score the exchange holds for the event - use it to avoid placing on a price that has not reacted to a goal yet. Only meaningful for football: for sports without a goal-style running score, and while no score is known yet, the server assumes `[0, 0]` and rejects any other value. Omit the field to skip the check.
type OrderCreateRequest_CurrentScore struct {
	union json.RawMessage
}

// OrderCreateRequestExchangeMode How the order interacts with the exchange. `make_and_take`: fill against the best available liquidity first; any remaining stake is advertised on the exchange at your price, while the order keeps taking newly available liquidity. `take_only`: only consume available liquidity; remaining stake is never advertised and other orders cannot match against it. `dark`: like `make_and_take`, but the advertised remaining stake is hidden from other customers - they can still match it when their price crosses yours, but they cannot see your price until then. There is no post-only mode: no order type rests in the book without also taking crossing liquidity.
type OrderCreateRequestExchangeMode string

// OrderEnvelope defines model for OrderEnvelope.
type OrderEnvelope struct {
	Data   *OrderResponse       `json:"data,omitempty"`
	Status *OrderEnvelopeStatus `json:"status,omitempty"`
}

// OrderEnvelopeStatus defines model for OrderEnvelope.Status.
type OrderEnvelopeStatus string

// OrderListEnvelope defines model for OrderListEnvelope.
type OrderListEnvelope struct {
	Data   *[]OrderResponse         `json:"data,omitempty"`
	Status *OrderListEnvelopeStatus `json:"status,omitempty"`
}

// OrderListEnvelopeStatus defines model for OrderListEnvelope.Status.
type OrderListEnvelopeStatus string

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	BetBarValues *map[string]interface{} `json:"bet_bar_values,omitempty"`

	// BetType Bet type string — see "Sports & bet types" in the introduction.
	BetType            *string        `json:"bet_type,omitempty"`
	BetTypeDescription *string        `json:"bet_type_description,omitempty"`
	Bets               *[]BetResponse `json:"bets,omitempty"`

	// CcyRate Exchange rate at order time
	CcyRate *float64 `json:"ccy_rate,omitempty"`

	// CloseReason Reason the order closed, e.g. order_filled, timed_out; null while open
	CloseReason *string    `json:"close_reason,omitempty"`
	Closed      *bool      `json:"closed,omitempty"`
	EventInfo   *EventInfo `json:"event_info,omitempty"`

	// ExchangeMode Exchange interaction mode as passed at creation; null on older orders
	ExchangeMode *OrderResponseExchangeMode `json:"exchange_mode,omitempty"`
	ExpiryTime   *time.Time                 `json:"expiry_time,omitempty"`
	KeepOpenIr   *bool                      `json:"keep_open_ir,omitempty"`
	Legs         *ParlayLegList             `json:"legs,omitempty"`
	OrderID      *int                       `json:"order_id,omitempty"`

	// OrderType Order type. `normal`, `lay` and `parlay` are the types placed through this API; `brokerage`, `cashout` and `custom` can appear on orders created by other channels. Treat it as an open set.
	OrderType     *OrderResponseOrderType `json:"order_type,omitempty"`
	PlacementTime *time.Time              `json:"placement_time,omitempty"`

	// Price Achieved price (null while open)
	Price      *float64    `json:"price,omitempty"`
	ProfitLoss *StakeTuple `json:"profit_loss,omitempty"`

	// Sport Sport code, or `parlay` for accumulators — see "Sports & bet types" in the introduction.
	Sport *string `json:"sport,omitempty"`

	// Stake Aggregate stake across matched bets
	Stake *StakeTuple `json:"stake,omitempty"`

	// Status Order lifecycle status: open, pending, failed, partial_void, full_void, done, or reconciled
	Status    *string  `json:"status,omitempty"`
	UserData  *string  `json:"user_data,omitempty"`
	WantPrice *float64 `json:"want_price,omitempty"`

	// WantStake [currency, amount] tuple, e.g. ["USDT", 115.38]. Generated as an untyped array because oapi-codegen cannot express an OpenAPI 3.1 tuple; magicmarkets.Stake is the typed equivalent.
	WantStake *StakeTuple `json:"want_stake,omitempty"`
}

// OrderResponseExchangeMode Exchange interaction mode as passed at creation; null on older orders
type OrderResponseExchangeMode string

// OrderResponseOrderType Order type. `normal`, `lay` and `parlay` are the types placed through this API; `brokerage`, `cashout` and `custom` can appear on orders created by other channels. Treat it as an open set.
type OrderResponseOrderType string

// ParlayLeg defines model for ParlayLeg.
type ParlayLeg struct {
	// BetType Bet type string — see "Sports & bet types" in the introduction.
	BetType            *string `json:"bet_type,omitempty"`
	BetTypeDescription *string `json:"bet_type_description,omitempty"`
	EventID            *string `json:"event_id,omitempty"`
	ID                 *int    `json:"id,omitempty"`

	// Outcome Leg settlement: `w` won, `l` lost, `v` void, `v/w` win-void, `l/v` void-loss, `l/w` loss-win (half outcomes), `unknown`, or null before settlement.
	Outcome *ParlayLegOutcome `json:"outcome,omitempty"`
	Price   *float64          `json:"price,omitempty"`

	// Sport Sport code — see "Sports & bet types" in the introduction.
	Sport *string `json:"sport,omitempty"`
}

// ParlayLegOutcome Leg settlement: `w` won, `l` lost, `v` void, `v/w` win-void, `l/v` void-loss, `l/w` loss-win (half outcomes), `unknown`, or null before settlement.
type ParlayLegOutcome string

// ParlayLegList defines model for ParlayLegList.
type ParlayLegList = []ParlayLeg

// PositionCashoutInfo Cashout valuation for the position. Present on every non-multirunner position. Cashout is offered on football only; on every other sport, and whenever cashout is otherwise unavailable, `allowed` is false and every value below is null.
type PositionCashoutInfo struct {
	Allowed bool `json:"allowed"`

	// Position Payoff grid the cashout is valued against
	Position *PositionGrid `json:"position"`

	// Reason Why cashout is unavailable, when it can be shared: `position_already_flat` or `insufficient_credit`.
	Reason *string `json:"reason"`

	// SmartCreditDelta Change in smart credit that taking the cashout would cause
	SmartCreditDelta *StakeTuple `json:"smart_credit_delta"`

	// Stake Stake currently at risk on the position
	Stake *StakeTuple `json:"stake"`

	// Valuation Amount offered to close the position now
	Valuation *StakeTuple `json:"valuation"`
}

// PositionComponentTotal Position for a standard bet type.
type PositionComponentTotal struct {
	// BetTypeDescription Bet type rendered for display
	BetTypeDescription string `json:"bet_type_description"`

	// GotPrice Average matched price, or null if nothing matched
	GotPrice *float64 `json:"got_price"`

	// GotStake [currency, amount] tuple, e.g. ["USDT", 115.38]. Generated as an untyped array because oapi-codegen cannot express an OpenAPI 3.1 tuple; magicmarkets.Stake is the typed equivalent.
	GotStake StakeTuple `json:"got_stake"`

	// UnknownPrice Average price of the bets whose outcome is still unknown
	UnknownPrice *float64 `json:"unknown_price"`

	// UnknownStake [currency, amount] tuple, e.g. ["USDT", 115.38]. Generated as an untyped array because oapi-codegen cannot express an OpenAPI 3.1 tuple; magicmarkets.Stake is the typed equivalent.
	UnknownStake StakeTuple `json:"unknown_stake"`
}

// PositionCustomBetTotal Position for a custom bet type, which carries its own grid instead of prices.
type PositionCustomBetTotal struct {
	// BetTypeDescription Bet type rendered for display
	BetTypeDescription string `json:"bet_type_description"`

	// GotStake [currency, amount] tuple, e.g. ["USDT", 115.38]. Generated as an untyped array because oapi-codegen cannot express an OpenAPI 3.1 tuple; magicmarkets.Stake is the typed equivalent.
	GotStake   StakeTuple    `json:"got_stake"`
	PayoffGrid *PositionGrid `json:"payoff_grid"`
}

// PositionEnvelope defines model for PositionEnvelope.
type PositionEnvelope struct {
	// Data Aggregate profit/loss position over the filtered orders. `sport`, `event_id` and `event_info` are present once the filters match at least one order.
	Data   *PositionResponse       `json:"data,omitempty"`
	Status *PositionEnvelopeStatus `json:"status,omitempty"`
}

// PositionEnvelopeStatus defines model for PositionEnvelope.Status.
type PositionEnvelopeStatus string

// PositionGrid Profit or loss per scoreline, in USDT: `values[home_score][away_score]`. The grid is square and its size depends on the sport.
type PositionGrid struct {
	// CcyCode Always USDT
	CcyCode string      `json:"ccy_code"`
	Values  [][]float64 `json:"values"`
}

// PositionResponse Aggregate profit/loss position over the filtered orders. `sport`, `event_id` and `event_info` are present once the filters match at least one order.
type PositionResponse struct {
	// CashoutInfo Cashout valuation for the position. Present on every non-multirunner position. Cashout is offered on football only; on every other sport, and whenever cashout is otherwise unavailable, `allowed` is false and every value below is null.
	CashoutInfo *PositionCashoutInfo `json:"cashout_info,omitempty"`
	EventID     *string              `json:"event_id,omitempty"`
	EventInfo   *EventInfo           `json:"event_info,omitempty"`

	// PayoffGrid Payoff from the matched bets, or null when every cell is zero
	PayoffGrid *PositionGrid `json:"payoff_grid"`
	Sport      *string       `json:"sport,omitempty"`

	// Totals Position per bet type, keyed by the unflipped bet type string
	Totals map[string]PositionResponse_Totals_AdditionalProperties `json:"totals"`

	// UnknownBetsNum Number of bets that could not be projected onto the grid
	UnknownBetsNum int `json:"unknown_bets_num"`

	// UnknownGrid Payoff from the bets counted in `unknown_bets_num`
	UnknownGrid *PositionGrid `json:"unknown_grid"`
}

// PositionResponse_Totals_AdditionalProperties defines model for PositionResponse.totals.AdditionalProperties.
type PositionResponse_Totals_AdditionalProperties struct {
	union json.RawMessage
}

// PriceLevel defines model for PriceLevel.
type PriceLevel struct {
	Effective *struct {
		// Max Maximum stake at this price level, or null
		Max *StakeTuple `json:"max,omitempty"`

		// Min Minimum stake at this price level, or null
		Min *StakeTuple `json:"min,omitempty"`

		// Price Decimal price
		Price *float64 `json:"price,omitempty"`
	} `json:"effective,omitempty"`
}

// StakeTuple [currency, amount] tuple, e.g. ["USDT", 115.38]. Generated as an untyped array because oapi-codegen cannot express an OpenAPI 3.1 tuple; magicmarkets.Stake is the typed equivalent.
type StakeTuple = []interface{}

// XRate defines model for XRate.
type XRate struct {
	// Ccy Currency code (e.g. USD, EUR, USDT)
	Ccy *string `json:"ccy,omitempty"`

	// Rate Exchange rate to USDT
	Rate *float64 `json:"rate,omitempty"`
}

// XRatesEnvelope defines model for XRatesEnvelope.
type XRatesEnvelope struct {
	Data   *[]XRate              `json:"data,omitempty"`
	Status *XRatesEnvelopeStatus `json:"status,omitempty"`
}

// XRatesEnvelopeStatus defines model for XRatesEnvelope.Status.
type XRatesEnvelopeStatus string

// Error401 Standard error response. The shape of `data` varies by `code` — see the **Errors** section in the introduction and the named examples on each endpoint's error responses.
type Error401 = ErrorEnvelope

// Error403 Standard error response. The shape of `data` varies by `code` — see the **Errors** section in the introduction and the named examples on each endpoint's error responses.
type Error403 = ErrorEnvelope

// Error429 Standard error response. The shape of `data` varies by `code` — see the **Errors** section in the introduction and the named examples on each endpoint's error responses.
type Error429 = ErrorEnvelope

// Error500 Standard error response. The shape of `data` varies by `code` — see the **Errors** section in the introduction and the named examples on each endpoint's error responses.
type Error500 = ErrorEnvelope

// PostV2HeartbeatsJSONBody defines parameters for PostV2Heartbeats.
type PostV2HeartbeatsJSONBody struct {
	// Timeout Seconds before the heartbeat expires
	Timeout int `json:"timeout"`
}

// GetV2OrdersParams defines parameters for GetV2Orders.
type GetV2OrdersParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Status Filter by status (open, pending, done, failed)
	Status *[]string `form:"status,omitempty" json:"status,omitempty"`

	// Sport Filter by sport code — see "Sports & bet types" in the introduction.
	Sport *[]string `form:"sport,omitempty" json:"sport,omitempty"`

	// EventID Filter by event ID
	EventID *[]string `form:"event_id,omitempty" json:"event_id,omitempty"`

	// OrderType Filter by order type (normal, lay, parlay)
	OrderType *[]string `form:"order_type,omitempty" json:"order_type,omitempty"`

	// DateFrom Start of date range (ISO 8601)
	DateFrom *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo End of date range (ISO 8601)
	DateTo *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`

	// Search Free-text search
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// PostV2OrdersCloseAllJSONBody defines parameters for PostV2OrdersCloseAll.
type PostV2OrdersCloseAllJSONBody struct {
	// EventID Only close orders on this event (requires sport)
	EventID *string `json:"event_id,omitempty"`

	// Sport Only close orders on this sport — see "Sports & bet types" in the introduction.
	Sport *string `json:"sport,omitempty"`
}

// PostV2OrdersCloseManyJSONBody defines parameters for PostV2OrdersCloseMany.
type PostV2OrdersCloseManyJSONBody struct {
	OrderIds []int `json:"order_ids"`
}

// PostV2OrdersCloseMany200JSONResponseBodyStatus defines parameters for PostV2OrdersCloseMany.
type PostV2OrdersCloseMany200JSONResponseBodyStatus string

// GetV2OrdersPositionParams defines parameters for GetV2OrdersPosition.
type GetV2OrdersPositionParams struct {
	Status    *[]string  `form:"status,omitempty" json:"status,omitempty"`
	Sport     *[]string  `form:"sport,omitempty" json:"sport,omitempty"`
	EventID   *[]string  `form:"event_id,omitempty" json:"event_id,omitempty"`
	OrderType *[]string  `form:"order_type,omitempty" json:"order_type,omitempty"`
	DateFrom  *time.Time `form:"date_from,omitempty" json:"date_from,omitempty"`
	DateTo    *time.Time `form:"date_to,omitempty" json:"date_to,omitempty"`
	Search    *string    `form:"search,omitempty" json:"search,omitempty"`

	// IncludeCashoutInfo Accepted for compatibility. `cashout_info` is currently returned on every position regardless of this flag.
	IncludeCashoutInfo *bool `form:"include_cashout_info,omitempty" json:"include_cashout_info,omitempty"`
}

// GetV2OrdersUpdatesParams defines parameters for GetV2OrdersUpdates.
type GetV2OrdersUpdatesParams struct {
	// UpdatedAtFrom Start of update window (ISO 8601). Must be at least 60 seconds in the past.
	UpdatedAtFrom time.Time `form:"updated_at_from" json:"updated_at_from"`

	// UpdatedAtTo End of update window (ISO 8601). Must be at least 60 seconds in the past and within 70 minutes of `updated_at_from`.
	UpdatedAtTo time.Time `form:"updated_at_to" json:"updated_at_to"`
}

// GetV2SportsSportBetTypesBetTypeParams defines parameters for GetV2SportsSportBetTypesBetType.
type GetV2SportsSportBetTypesBetTypeParams struct {
	// HomeTeam Home team name for display labels
	HomeTeam *string `form:"home_team,omitempty" json:"home_team,omitempty"`

	// AwayTeam Away team name for display labels
	AwayTeam *string `form:"away_team,omitempty" json:"away_team,omitempty"`
}

// GetV2StreamParams defines parameters for GetV2Stream.
type GetV2StreamParams struct {
	// APIKey API key (the `X-Api-Key` value)
	APIKey string `form:"api_key" json:"api_key"`

	// Lang Language for event/competition names
	Lang *GetV2StreamParamsLang `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetV2StreamParamsLang defines parameters for GetV2Stream.
type GetV2StreamParamsLang string

// PostV2BetslipsJSONRequestBody defines body for PostV2Betslips for application/json ContentType.
type PostV2BetslipsJSONRequestBody = BetslipCreateRequest

// PostV2HeartbeatsJSONRequestBody defines body for PostV2Heartbeats for application/json ContentType.
type PostV2HeartbeatsJSONRequestBody PostV2HeartbeatsJSONBody

// PostV2OrdersJSONRequestBody defines body for PostV2Orders for application/json ContentType.
type PostV2OrdersJSONRequestBody = OrderCreateRequest

// PostV2OrdersCloseAllJSONRequestBody defines body for PostV2OrdersCloseAll for application/json ContentType.
type PostV2OrdersCloseAllJSONRequestBody PostV2OrdersCloseAllJSONBody

// PostV2OrdersCloseManyJSONRequestBody defines body for PostV2OrdersCloseMany for application/json ContentType.
type PostV2OrdersCloseManyJSONRequestBody PostV2OrdersCloseManyJSONBody

// AsEventResultMatch returns the union data inside the EventInfo_Result as a EventResultMatch
func (t EventInfo_Result) AsEventResultMatch() (EventResultMatch, error) {
	var body EventResultMatch
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventResultMatch overwrites any union data inside the EventInfo_Result as the provided EventResultMatch
func (t *EventInfo_Result) FromEventResultMatch(v EventResultMatch) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventResultMatch performs a merge with any union data inside the EventInfo_Result, using the provided EventResultMatch
func (t *EventInfo_Result) MergeEventResultMatch(v EventResultMatch) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventResultTennis returns the union data inside the EventInfo_Result as a EventResultTennis
func (t EventInfo_Result) AsEventResultTennis() (EventResultTennis, error) {
	var body EventResultTennis
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventResultTennis overwrites any union data inside the EventInfo_Result as the provided EventResultTennis
func (t *EventInfo_Result) FromEventResultTennis(v EventResultTennis) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventResultTennis performs a merge with any union data inside the EventInfo_Result, using the provided EventResultTennis
func (t *EventInfo_Result) MergeEventResultTennis(v EventResultTennis) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventResultHockey returns the union data inside the EventInfo_Result as a EventResultHockey
func (t EventInfo_Result) AsEventResultHockey() (EventResultHockey, error) {
	var body EventResultHockey
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventResultHockey overwrites any union data inside the EventInfo_Result as the provided EventResultHockey
func (t *EventInfo_Result) FromEventResultHockey(v EventResultHockey) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventResultHockey performs a merge with any union data inside the EventInfo_Result, using the provided EventResultHockey
func (t *EventInfo_Result) MergeEventResultHockey(v EventResultHockey) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventResultTableTennis returns the union data inside the EventInfo_Result as a EventResultTableTennis
func (t EventInfo_Result) AsEventResultTableTennis() (EventResultTableTennis, error) {
	var body EventResultTableTennis
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventResultTableTennis overwrites any union data inside the EventInfo_Result as the provided EventResultTableTennis
func (t *EventInfo_Result) FromEventResultTableTennis(v EventResultTableTennis) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventResultTableTennis performs a merge with any union data inside the EventInfo_Result, using the provided EventResultTableTennis
func (t *EventInfo_Result) MergeEventResultTableTennis(v EventResultTableTennis) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventResultMultirunner returns the union data inside the EventInfo_Result as a EventResultMultirunner
func (t EventInfo_Result) AsEventResultMultirunner() (EventResultMultirunner, error) {
	var body EventResultMultirunner
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventResultMultirunner overwrites any union data inside the EventInfo_Result as the provided EventResultMultirunner
func (t *EventInfo_Result) FromEventResultMultirunner(v EventResultMultirunner) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventResultMultirunner performs a merge with any union data inside the EventInfo_Result, using the provided EventResultMultirunner
func (t *EventInfo_Result) MergeEventResultMultirunner(v EventResultMultirunner) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventInfo_Result) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventInfo_Result) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOrderCreateRequestCurrentScore0 returns the union data inside the OrderCreateRequest_CurrentScore as a OrderCreateRequestCurrentScore0
func (t OrderCreateRequest_CurrentScore) AsOrderCreateRequestCurrentScore0() (OrderCreateRequestCurrentScore0, error) {
	var body OrderCreateRequestCurrentScore0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOrderCreateRequestCurrentScore0 overwrites any union data inside the OrderCreateRequest_CurrentScore as the provided OrderCreateRequestCurrentScore0
func (t *OrderCreateRequest_CurrentScore) FromOrderCreateRequestCurrentScore0(v OrderCreateRequestCurrentScore0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOrderCreateRequestCurrentScore0 performs a merge with any union data inside the OrderCreateRequest_CurrentScore, using the provided OrderCreateRequestCurrentScore0
func (t *OrderCreateRequest_CurrentScore) MergeOrderCreateRequestCurrentScore0(v OrderCreateRequestCurrentScore0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OrderCreateRequest_CurrentScore) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OrderCreateRequest_CurrentScore) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPositionComponentTotal returns the union data inside the PositionResponse_Totals_AdditionalProperties as a PositionComponentTotal
func (t PositionResponse_Totals_AdditionalProperties) AsPositionComponentTotal() (PositionComponentTotal, error) {
	var body PositionComponentTotal
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPositionComponentTotal overwrites any union data inside the PositionResponse_Totals_AdditionalProperties as the provided PositionComponentTotal
func (t *PositionResponse_Totals_AdditionalProperties) FromPositionComponentTotal(v PositionComponentTotal) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePositionComponentTotal performs a merge with any union data inside the PositionResponse_Totals_AdditionalProperties, using the provided PositionComponentTotal
func (t *PositionResponse_Totals_AdditionalProperties) MergePositionComponentTotal(v PositionComponentTotal) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPositionCustomBetTotal returns the union data inside the PositionResponse_Totals_AdditionalProperties as a PositionCustomBetTotal
func (t PositionResponse_Totals_AdditionalProperties) AsPositionCustomBetTotal() (PositionCustomBetTotal, error) {
	var body PositionCustomBetTotal
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPositionCustomBetTotal overwrites any union data inside the PositionResponse_Totals_AdditionalProperties as the provided PositionCustomBetTotal
func (t *PositionResponse_Totals_AdditionalProperties) FromPositionCustomBetTotal(v PositionCustomBetTotal) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePositionCustomBetTotal performs a merge with any union data inside the PositionResponse_Totals_AdditionalProperties, using the provided PositionCustomBetTotal
func (t *PositionResponse_Totals_AdditionalProperties) MergePositionCustomBetTotal(v PositionCustomBetTotal) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PositionResponse_Totals_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PositionResponse_Totals_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
